from . import product_category_ept
from . import product_uom_category
from . import product_uom_ept
from . import product_ept
from . import res_partner_ept
from . import sale_order_ept
from . import sale_order_line_ept
from . import crm_team_ept
from . import crm_lead_ept
from . import crm_lead_line_ept